export function generateRandomString(n) {
  const chars =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  let result = "";
  for (let i = 0; i < n; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

export const projects = [
  {
    no: 0,
    name: "Quick call",
    url: "quickcall",
    participants: [
      {
        rol: "developer",
        name: "Luis Alberto Salas",
        linkedin: "https://www.linkedin.com/in/luis-salcedo-salas/",
      },
      {
        rol: "developer",
        name: "Francisco Huertas Cruz",
        linkedin: "https://www.linkedin.com/in/francisco-huertas-cruz/",
      },
      {
        rol: "developer",
        name: "Jesus Osorio Jimenez",
        linkedin: "https://www.linkedin.com/in/jesus-david-osorio-jimenez/",
      },
    ],
    responsibilities: 0,
    technologies: {
      frontend: ["react", "redux", "sass", "JS", "socket"],
      backend: ["node", "sendgrid", "cloudinary", "stripe"],
      database: ["mongodb"],
      test: ["jest", "cypress"],
    },
    characteristics: 7,
    backend: "https://github.com/JesusOsorioJ/Quick-call-Backend",
    frontend: "https://github.com/Luis-S-S/quick-call",
    webpage: "https://quickcall.netlify.app/",
    imageswebpages: [
      "landing",
      "consulta",
      "trabajos",
      "chat",
      "pasarelapago",
      "login",
    ],
    videopage: null,
  },
  {
    no: 1,
    name: "Mi app",
    url: "miapp",
    participants: [
      {
        rol: "developer",
        name: "Jesus Osorio Jimenez",
        linkedin: "https://www.linkedin.com/in/jesus-david-osorio-jimenez/",
      },
    ],
    responsibilities: 0,
    technologies: {
      frontend: ["react", "sass", "redux", "JS"],
      backend: [],
      database: ["firebase"],
      test: [],
    },
    characteristics: 5,
    backend: null,
    frontend: "https://github.com/JesusOsorioJ/my-app",
    webpage: "https://my-appcreate.vercel.app/",
    imageswebpages: [
      "cuestionario1",
      "signup",
      "curso1",
      "envivo",
      "curso",
      "suscripcion",
    ],
    videopage: "https://www.youtube.com/watch?v=QLfULI03pl0",
  },
  {
    no: 2,
    name: "Maker Hub (en desarrollo)",
    url: "makerhub",
    participants: [
      {
        rol: "developer",
        name: "German Escobar ",
        linkedin: "https://www.linkedin.com/in/germanescobar/",
      },
      {
        rol: "developer",
        name: "Jesus Osorio Jimenez",
        linkedin: "https://www.linkedin.com/in/jesus-david-osorio-jimenez/",
      },
    ],
    responsibilities: 7,
    technologies: {
      frontend: ["vite", "bootstrap"],
      backend: ["prisma", "TS", "express", "node"],
      database: ["postgresql"],
      test: [],
    },
    characteristics: 5,
    backend: null,
    frontend: null,
    webpage: null,
    videopage: null,
    imageswebpages: [
      "login",
      "makerview",
      "makernew",
      "makerupdate",
      "admindetails",
      "adminUpdate",
      "adminview",
      "delete",
    ],
  },
  {
    no: 3,
    name: "ArchiBige Doc",
    url: "archibige",
    participants: [
      { rol: "company", name: "Ilia Sofia Castilla", linkedin: "" },
      {
        rol: "developer",
        name: "Jesus Osorio Jimenez",
        linkedin: "https://www.linkedin.com/in/jesus-david-osorio-jimenez/",
      },
    ],
    responsibilities: 0,
    technologies: {
      frontend: ["angular", "tailwind", "TS", "gapsap"],
      backend: [],
      database: [],
      test: [],
    },
    characteristics: 5,
    backend: null,
    frontend: "https://github.com/JesusOsorioJ/empresasofia",
    webpage: "https://pgdi.vercel.app/",
    imageswebpages: ["landing", "somos", "servicios", "opiniones", "ubicacion"],
    videopage: null,
  },
  {
    no: 4,
    name: "Test English",
    url: "testenglish",
    participants: [
      {
        rol: "developer",
        name: "Jesus Osorio Jimenez",
        linkedin: "https://www.linkedin.com/in/jesus-david-osorio-jimenez/",
      },
    ],
    responsibilities: 0,
    technologies: {
      frontend: ["nextjs", "TS", "tailwind", "react hook form", "eslint"],
      backend: ["prisma"],
      database: ["postgresql"],
      test: [],
    },
    characteristics: 5,
    backend: null,
    frontend: "https://github.com/JesusOsorioJ/testenglish",
    webpage: "https://testenglish.vercel.app/",
    imageswebpages: ["landing", "login", "loginuser", "testEn", "filter"],
    videopage: null,
  },
  {
    no: 5,
    name: "Mega Tv",
    url: "megatv",
    participants: [
      {
        rol: "developer",
        name: "Jesus Osorio Jimenez",
        linkedin: "https://www.linkedin.com/in/jesus-david-osorio-jimenez/",
      },
    ],
    responsibilities: 0,
    technologies: {
      frontend: ["react", "sass", "JS", "redux"],
      backend: ["node", "nodemon", "express"],
      database: ["mongodb"],
      test: [],
    },
    characteristics: 5,
    backend: "https://github.com/JesusOsorioJ/megatvback",
    frontend: "https://github.com/JesusOsorioJ/megatv",
    webpage: "https://megatv.vercel.app/",
    imageswebpages: ["landing", "great", "plan", "address"],
    videopage: null,
  },
  {
    no: 6,
    name: "Backend GraphQl",
    url: "graphql",
    participants: [
      {
        rol: "developer",
        name: "Jesus Osorio Jimenez",
        linkedin: "https://www.linkedin.com/in/jesus-david-osorio-jimenez/",
      },
    ],
    responsibilities: 0,
    technologies: {
      frontend: [],
      backend: ["graphql", "node", "express", "nodemon"],
      database: ["mongodb"],
      test: [],
    },
    characteristics: 7,
    frontend: null,
    backend: "https://github.com/JesusOsorioJ/GraphQlexercise",
    webpage: "https://graphqlexercise.up.railway.app/graphql",
    imageswebpages: [
      "createuser",
      "allquerymutation",
      "createdocument",
      "createcontact",
      "allname",
      "allmutation",
    ],
    videopage: null,
  },
  {
    no: 7,
    name: "Dreadful",
    url: "dreadful",
    participants: [
      {
        rol: "developer",
        name: "Jesus Osorio Jimenez",
        linkedin: "https://www.linkedin.com/in/jesus-david-osorio-jimenez/",
      },
    ],
    responsibilities: 0,
    technologies: {
      frontend: ["angular", "TS", "tailwind"],
      backend: [],
      database: [],
      test: [],
    },
    characteristics: 4,
    frontend: "https://github.com/JesusOsorioJ/dreadfulmovie",
    backend: null,
    webpage: "https://dreadfulmovie.vercel.app/",
    imageswebpages: ["pagination", "filter", "landing", "filter1"],
    videopage: null,
    test: [],
  },
  {
    no: 8,
    name: "Crud Nextjs",
    url: "crudnext",
    participants: [
      {
        rol: "developer",
        name: "Jesus Osorio Jimenez",
        linkedin: "https://www.linkedin.com/in/jesus-david-osorio-jimenez/",
      },
    ],
    responsibilities: 0,
    technologies: {
      frontend: ["nextjs", "JS", "tailwind"],
      backend: [],
      database: ["mysql"],
      test: [],
    },
    characteristics: 4,
    frontend: "https://github.com/JesusOsorioJ/crudnext",
    backend: null,
    webpage: "https://crudnext-mu.vercel.app/",
    imageswebpages: ["landing", "addnew", "edit"],
    videopage: null,
  },
  {
    no: 9,
    name: "Crud IGM",
    url: "igm",
    participants: [
      {
        rol: "developer",
        name: "Jesus Osorio Jimenez",
        linkedin: "https://www.linkedin.com/in/jesus-david-osorio-jimenez/",
      },
    ],
    responsibilities: 0,
    technologies: {
      frontend: ["vuejs", "JS", "vuex"],
      backend: ["laravel", "PHP"],
      database: ["mysql"],
      test: ["PHPunit"],
    },
    characteristics: 4,
    frontend: "https://github.com/JesusOsorioJ/igmfront",
    backend: "https://github.com/JesusOsorioJ/igmback",
    webpage: "https://igmfront.vercel.app/",
    imageswebpages: ["login", "table", "createnote"],
    videopage: null,
  },
  {
    no: 10,
    name: "Quickbet movies",
    url: "quickbet",
    participants: [
      {
        rol: "developer",
        name: "Jesus Osorio Jimenez",
        linkedin: "https://www.linkedin.com/in/jesus-david-osorio-jimenez/",
      },
    ],
    responsibilities: 0,
    technologies: {
      frontend: ["nextjs", "JS", "zustand"],
      backend: ["nestjs", "bcryptjs"],
      database: ["postgresql"],
      test: [],
    },
    characteristics: 5,
    frontend: "https://github.com/JesusOsorioJ/front-tmdb",
    backend: "https://github.com/JesusOsorioJ/back-tmdb",
    webpage: "https://front-tmdb.vercel.app/",
    imageswebpages: ["register", "favorites", "details"],
    videopage: null,
  },
  {
    no: 11,
    name: "Laravel app",
    url: "laravelapp",
    participants: [
      {
        rol: "developer",
        name: "Jesus Osorio Jimenez",
        linkedin: "https://www.linkedin.com/in/jesus-david-osorio-jimenez/",
      },
    ],
    responsibilities: 0,
    technologies: {
      frontend: [],
      backend: ["laravel", "PHP", "node", "swagger"],
      database: ["mysql", "mongodb"],
      test: ["PHPunit"],
    },
    characteristics: 4,
    frontend: "https://github.com/JesusOsorioJ/laravel-app",
    backend: null,
    webpage: null,
    imageswebpages: ["cuentas", "pedidos"],
    videopage: null,
  },
  {
    no: 12,
    name: "Next task system",
    url: "nexttasksystem",
    participants: [
      {
        rol: "developer",
        name: "Jesus Osorio Jimenez",
        linkedin: "https://www.linkedin.com/in/jesus-david-osorio-jimenez/",
      },
    ],
    responsibilities: 0,
    technologies: {
      frontend: ["nextjs", "socket"],
      backend: ["TS"],
      database: ["mysql", "prisma"],
      test: ["jest"],
    },
    characteristics: 5,
    frontend:
      "https://github.com/JesusOsorioJ/nextjs-task-system/tree/trunk/nextjs-task-system",
    backend: null,
    webpage: null,
    imageswebpages: ["taskfront", "login", "task", "user", "test"],
    videopage: null,
  },
  {
    no: 13,
    name: "Evalart",
    url: "evalart",
    participants: [
      {
        rol: "developer",
        name: "Jesus Osorio Jimenez",
        linkedin: "https://www.linkedin.com/in/jesus-david-osorio-jimenez/",
      },
    ],
    responsibilities: 0,
    technologies: {
      frontend: [],
      backend: ["java", "maven", "swagger"],
      database: ["mongodb"],
      test: [],
    },
    characteristics: 4,
    frontend: null,
    backend: "https://github.com/JesusOsorioJ/evalart",
    webpage: null,
    imageswebpages: ["terminal", "crud"],
    videopage: null,
  },
  {
    no: 14,
    name: "Runa",
    url: "runa",
    participants: [
      {
        rol: "developer",
        name: "Jesus Osorio Jimenez",
        linkedin: "https://www.linkedin.com/in/jesus-david-osorio-jimenez/",
      },
    ],
    responsibilities: 0,
    technologies: {
      frontend: ["vite", "TS", "tailwind"],
      backend: ["JS", "node", "docker"],
      database: ["postgresql"],
      test: [],
    },
    characteristics: 4,
    frontend: "https://github.com/JesusOsorioJ/runa",
    backend: "https://github.com/JesusOsorioJ/runa",
    webpage: null,
    imageswebpages: ["terminal", "docker", "maquetacion"],
    videopage: null,
  },
  {
    no: 15,
    name: "Pocket",
    url: "pocket",
    participants: [
      {
        rol: "developer",
        name: "Jesus Osorio Jimenez",
        linkedin: "https://www.linkedin.com/in/jesus-david-osorio-jimenez/",
      },
    ],
    responsibilities: 0,
    technologies: {
      frontend: ["react", "TS", "tailwind", "i18next", "socket"],
      backend: ["node", "express", "swagger"],
      database: ["prisma"],
      test: [],
    },
    characteristics: 3,
    frontend: "https://github.com/JesusOsorioJ/pocket",
    backend: "https://github.com/JesusOsorioJ/pocket",
    webpage: "https://pocket-indol.vercel.app/",
    imageswebpages: ["chatbot", "eliminar", "temas"],
    videopage: null,
  },
  {
    no: 16,
    name: "Portafolio",
    url: "portfolio",
    participants: [
      {
        rol: "developer",
        name: "Jesus Osorio Jimenez",
        linkedin: "https://www.linkedin.com/in/jesus-david-osorio-jimenez/",
      },
    ],
    responsibilities: 0,
    technologies: {
      frontend: ["angular", "swiper", "i18next", "TS", "tailwind", "gsap"],
      backend: [],
      database: [],
      test: [],
    },
    characteristics: 3,
    frontend: "https://github.com/JesusOsorioJ/portfolio",
    backend: null,
    webpage: "https://jesusosorio1.vercel.app/",
    imageswebpages: ["landing", "proyectos", "detalleProyecto", "temasOscuroClaro", "responsive"],
    videopage: null,
  },
  {
    no: 17,
    name: "Mg panel",
    url: "mgpanel",
    participants: [
      {
        rol: "developer",
        name: "Jesus Osorio Jimenez",
        linkedin: "https://www.linkedin.com/in/jesus-david-osorio-jimenez/",
      },
    ],
    responsibilities: 0,
    technologies: {
      frontend: ["vite", "TS", "tailwind", "i18next"],
      backend: [],
      database: [],
      test: [],
    },
    characteristics: 3,
    frontend: "https://github.com/JesusOsorioJ/intentoHtml",
    backend: null,
    webpage: "https://intento-html.vercel.app/",
    imageswebpages: ["landing", "swiper", "themes"],
    videopage: null,
  },
];

export const technologies = {
  frontend: [
    "JS",
    "TS",
    "react",
    "nextjs",
    "vite",
    "angular",
    "bootstrap",
    "tailwind",
    "sass",
    "socket",
    "redux",
    "gapsap",
  ],
  backend: [
    "TS",
    "node",
    "express",
    "JSDoc",
    "swagger",
    "stripe",
    "sendgrid",
    "cloudinary",
    "graphql",
    "nodemon",
    "eslint",
    "express-validator",
  ],
  database: ["mongodb", "prisma", "firebase", "postgresql", "mysql"],
  test: ["jest", "cypress", "mocha", "chai"],
};
